# Algortihm Parameters
alpha: 0.1
gamma: 0.8
epsilon: 0.9
epsilon_discount: 0.999 # 1098 eps to reach 0.1
nepisodes: 100000
nsteps: 1000

# Input type
control_type: vel #traj_vel or vel

# Environment Parameters
desired_pose:
    x: 0.0
    y: 0.0
    z: 1.0

max_height: 3.0   # in meters
min_height: 0.5   # in meters
running_step: 0.0010   # in seconds

observations: # Observations you want to use for the learning
  - shp_joint_ang
  - shl_joint_ang
  - elb_joint_ang
  - wr1_joint_ang
  - wr2_joint_ang
  - wr3_joint_ang
  - shp_joint_vel
  - shl_joint_vel
  - elb_joint_vel
  - wr1_joint_vel
  - wr2_joint_vel
  - wr3_joint_vel
  - eef_x
  - eef_y
  - eef_z

init_joint_pose:
  shp: -2.873
  shl: 0.0
  elb: 6.28
  wr1: 1.21
  wr2: 1.264
  wr3: -0.97

joint_limits_array:
  shp_max: 1.0
  shp_min: -1.0
  shl_max: 1.0
  shl_min: -1.0
  elb_max: 1.0
  elb_min: -1.0
  wr1_max: 1.0
  wr1_min: -1.0
  wr2_max: 1.0
  wr2_min: -1.0
  wr3_max: 1.0
  wr3_min: -1.0

episode_done_criteria:
  - minimum_height
  #- monoped_vertical_orientation
